### ISSUE TITLE
breathSpeechCompare.m

### ISSUE THREAD

**Issue by divnami** [alexisdmacintyre/SpeechBreathingToolbox#1]
It works for my case, great work I think.
I just had an issue using Matlab 2023b in lines that I solved putting **round** function before

118    speechVector = spOut(round(beg(ii)):round(en(ii)));
119    breathVector = breathBelt(round(beg(ii)):round(en(ii)));
120   og_beg = round(beg(ii));
121    og_en = round(en(ii));

225    new_beg = round(beg(ii)) + a(l);
225    new_en = round(beg(ii)) + b(l);

because _"Integer operands are required for colon operator when used as index"_

[breathSpeechCompare.txt](https://github.com/alexisdmacintyre/SpeechBreathingToolbox/files/12834955/breathSpeechCompare.txt)

**Comment by alexisdmacintyre** [comment]
Thanks @divnami for the catch. Glad to hear it's of use for you
